framenumber, U32_Type
command.roll, F32_Type
command.pitch, F32_Type
baro_altitude_0, F32_Type
baro_altitude_1, F32_Type
airspeed_0, F32_Type
airspeed_1, F32_Type
temperature, F32_Type
coefficient_changed_value, F32_Type
coefficient_changed_index, S16_Type
outer_loop_mode, U32_Type
annunciator_states, U8_Type
