#!/bin/bash

map()
{
    dev=$1
    alias=$2
    echo "map: $dev -> $alias"
    echo 0 "$(blockdev --getsize $dev)" mymap $dev 0 "$(blockdev --getsize $dev)"|dmsetup create $alias
}

unmap()
{
    alias=$1
    echo "unmap $alias"
    dmsetup remove $alias
}

clr()
{
    echo "clear"
    echo 1 > "/sys/kernel/my_mapper/foo"
}

dmp()
{
    echo "dump"
    cat "/sys/kernel/my_mapper/foo"
}

show() 
{
    echo "show"
    dmsetup table
}

usage()
{
    echo ""
    echo "my-map is a utility for monitoring device IO patterns and latencies"
    echo ""
    echo "	my-map map /dev/sdc mydc"
    echo "	my-map unmap mydc"
    echo "	my-map show"
    echo "	my-map clear"
    echo "	my-map dump"
    echo ""
}

#must specify an operation
if [ "$1" == "" ]; then
    usage
    exit 1
else
    OPERATION=$1
fi

case "$OPERATION" in
    "map")
        dev=$2
        alias=$3
        map $dev $alias
        ;;
    "unmap")
        alias=$2
        unmap $alias
        ;;
    "clear")
        clr
        ;;
    "dump")
        dmp
        ;;
    "show")
        show
        ;;
    *)
        echo "???"
        ;;
esac

exit

