CXX=g++
RM=rm -f
CPPFLAGS=-g -c -Wall -pthread -O0 -std=gnu++0x
LDFLAGS=-pthread -o

OBJS=pdisk.o
HEADERS=

all:	pdisk

pdisk: $(OBJS)
	$(CXX) $(LDFLAGS) $@ $+ -Wl,-Map=$@.map

%.o:%.cc
	$(CXX) $(CPPFLAGS) $+

$(OBJS): $(HEADERS)

clean:
	$(RM) pdisk.o pdisk *.map

