#!/bin/bash

# http://iverilog.wikia.com/wiki/Using_VPI
#iverilog -o traffic traffic_tb.v traffic.v
#vvp traffic

/opt/local/bin/iverilog -o counter counter_tb.v counter.v
/opt/local/bin/vvp counter

