#!/bin/bash

# g++ -std=c++0x -I /usr/local/include -L/opt/local/lib -lboost_system-mt lambda.cc
#g++ -std=c++0x -I /usr/local/include -L/opt/local/lib lambda.cc 
g++ -std=c++11 -I /usr/local/include -lboost_regex -L/opt/local/lib regex.cc
