#!/bin/bash

#g++ -std=c++0x -I /usr/local/include -L/opt/local/lib -lboost_system-mt dev.cpp
g++ -std=c++0x -I /usr/local/include -L/opt/local/lib  -L/usr/local/libboost_serialization-mt.a  dev.cpp
#g++ -std=c++11 -I /usr/local/include -lboost_regex -L/opt/local/lib regex.cc
