#!/bin/bash
#
# This script creates the hal_my_uart Board Support Package (BSP).

BSP_TYPE=hal
BSP_DIR=.
SOPC_DIR=../../..

# Set of arguments for the bsp 
NIOS2_BSP_ARGS_1="--set hal.max_file_descriptors 4 --set hal.enable_small_c_library true --set hal.sys_clk_timer sysclk_timer --set hal.timestamp_timer none --set hal.enable_exit true --set hal.enable_c_plus_plus false "

NIOS2_BSP_ARGS_2="--set hal.linker.enable_alt_load_copy_rwdata false --set hal.enable_lightweight_device_driver_api false --set hal.enable_sim_optimize false --set hal.enable_reduced_device_drivers false  --set hal.make.bsp_cflags_optimization '-O1'"

# Run nios2-bsp utility to create a HAL BSP in this directory
# for the system with a .sopc file in $SOPC_DIR.

cmd="nios2-bsp $BSP_TYPE $BSP_DIR $SOPC_DIR $NIOS2_BSP_ARGS_1 $NIOS2_BSP_ARGS_2 --librarian-path $,$SOPC_DIR/ip/my_uart --log hal_my_uart_build_log.txt --set hal.log_port jtag_uart --set hal.log_flags 3 --script hal_my_uart.tcl --default_stdio uart1 $@"

echo "create-this-bsp: Running \"$cmd\""
$cmd || {
    echo "$cmd failed"
    exit 1
}

echo "create-this-bsp: Running make"
make
