/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu' in SOPC Builder design 'system'
 * SOPC Builder design path: ../../../system.sopcinfo
 *
 * Generated: Tue Mar 24 16:48:13 MYT 2015
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00001020
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0xf
#define ALT_CPU_DCACHE_BYPASS_MASK 0x80000000
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 2048
#define ALT_CPU_EIC_PRESENT
#define ALT_CPU_EXCEPTION_ADDR 0x00004020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0xf
#define ALT_CPU_NAME "cpu"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 7
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00004000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00001020
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0xf
#define NIOS2_DCACHE_BYPASS_MASK 0x80000000
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 2048
#define NIOS2_EIC_PRESENT
#define NIOS2_EXCEPTION_ADDR 0x00004020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0xf
#define NIOS2_NUM_OF_SHADOW_REG_SETS 7
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00004000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_AVALON_UART
#define __ALTERA_NIOS2_GEN2
#define __ALTERA_VIC


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/jtag_uart"
#define ALT_LOG_PORT_BASE 0x20
#define ALT_LOG_PORT_DEV jtag_uart
#define ALT_LOG_PORT_IS_JTAG_UART
#define ALT_LOG_PORT_PRESENT
#define ALT_LOG_PORT_TYPE ALTERA_AVALON_JTAG_UART
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/uart1"
#define ALT_STDERR_BASE 0x80
#define ALT_STDERR_DEV uart1
#define ALT_STDERR_IS_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_uart"
#define ALT_STDIN "/dev/uart1"
#define ALT_STDIN_BASE 0x80
#define ALT_STDIN_DEV uart1
#define ALT_STDIN_IS_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_uart"
#define ALT_STDOUT "/dev/uart1"
#define ALT_STDOUT_BASE 0x80
#define ALT_STDOUT_DEV uart1
#define ALT_STDOUT_IS_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_uart"
#define ALT_SYSTEM_NAME "system"


/*
 * altera_vic_driver configuration
 *
 */

#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_1 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_2 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_3 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_4 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_5 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_6 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_7 0
#define ALTERA_VIC_DRIVER_ISR_PREEMPTION_ENABLED
#define ALTERA_VIC_DRIVER_LINKER_SECTION .text
#define ALTERA_VIC_DRIVER_VIC_0_IRQ0_RIL 15
#define ALTERA_VIC_DRIVER_VIC_0_IRQ0_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ0_RRS 7
#define ALTERA_VIC_DRIVER_VIC_0_IRQ10_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ10_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ10_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ11_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ11_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ11_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ12_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ12_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ12_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ13_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ13_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ13_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ14_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ14_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ14_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ15_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ15_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ15_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ16_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ16_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ16_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ17_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ17_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ17_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ18_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ18_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ18_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ19_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ19_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ19_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ1_RIL 14
#define ALTERA_VIC_DRIVER_VIC_0_IRQ1_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ1_RRS 6
#define ALTERA_VIC_DRIVER_VIC_0_IRQ20_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ20_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ20_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ21_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ21_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ21_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ22_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ22_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ22_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ23_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ23_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ23_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ24_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ24_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ24_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ25_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ25_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ25_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ26_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ26_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ26_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ27_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ27_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ27_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ28_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ28_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ28_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ29_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ29_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ29_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ2_RIL 13
#define ALTERA_VIC_DRIVER_VIC_0_IRQ2_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ2_RRS 5
#define ALTERA_VIC_DRIVER_VIC_0_IRQ30_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ30_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ30_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ31_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ31_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ31_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ3_RIL 12
#define ALTERA_VIC_DRIVER_VIC_0_IRQ3_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ3_RRS 4
#define ALTERA_VIC_DRIVER_VIC_0_IRQ4_RIL 11
#define ALTERA_VIC_DRIVER_VIC_0_IRQ4_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ4_RRS 3
#define ALTERA_VIC_DRIVER_VIC_0_IRQ5_RIL 10
#define ALTERA_VIC_DRIVER_VIC_0_IRQ5_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ5_RRS 2
#define ALTERA_VIC_DRIVER_VIC_0_IRQ6_RIL 9
#define ALTERA_VIC_DRIVER_VIC_0_IRQ6_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ6_RRS 1
#define ALTERA_VIC_DRIVER_VIC_0_IRQ7_RIL 8
#define ALTERA_VIC_DRIVER_VIC_0_IRQ7_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ7_RRS 1
#define ALTERA_VIC_DRIVER_VIC_0_IRQ8_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ8_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ8_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ9_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ9_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ9_RRS 0
#define VIC_0_VEC_SIZE 16
#define VIC_0_VEC_TBL_BASE VIC_0_VECTOR_TABLE


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 4
#define ALT_SYS_CLK SYSCLK_TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x20
#define JTAG_UART_IRQ 1
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * onchip_memory configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_BASE 0x4000
#define ONCHIP_MEMORY_CONTENTS_INFO ""
#define ONCHIP_MEMORY_DUAL_PORT 0
#define ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_INIT_CONTENTS_FILE "system_onchip_memory"
#define ONCHIP_MEMORY_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY_IRQ -1
#define ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_SIZE_VALUE 16384
#define ONCHIP_MEMORY_SPAN 16384
#define ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY_WRITABLE 1


/*
 * sysclk_timer configuration
 *
 */

#define ALT_MODULE_CLASS_sysclk_timer altera_avalon_timer
#define SYSCLK_TIMER_ALWAYS_RUN 0
#define SYSCLK_TIMER_BASE 0x40
#define SYSCLK_TIMER_COUNTER_SIZE 32
#define SYSCLK_TIMER_FIXED_PERIOD 0
#define SYSCLK_TIMER_FREQ 50000000
#define SYSCLK_TIMER_IRQ 0
#define SYSCLK_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SYSCLK_TIMER_LOAD_VALUE 499999
#define SYSCLK_TIMER_MULT 0.001
#define SYSCLK_TIMER_NAME "/dev/sysclk_timer"
#define SYSCLK_TIMER_PERIOD 10
#define SYSCLK_TIMER_PERIOD_UNITS "ms"
#define SYSCLK_TIMER_RESET_OUTPUT 0
#define SYSCLK_TIMER_SNAPSHOT 1
#define SYSCLK_TIMER_SPAN 32
#define SYSCLK_TIMER_TICKS_PER_SEC 100
#define SYSCLK_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define SYSCLK_TIMER_TYPE "altera_avalon_timer"


/*
 * sysid configuration
 *
 */

#define ALT_MODULE_CLASS_sysid altera_avalon_sysid_qsys
#define SYSID_BASE 0x10
#define SYSID_ID 0
#define SYSID_IRQ -1
#define SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_NAME "/dev/sysid"
#define SYSID_SPAN 8
#define SYSID_TIMESTAMP 1427186341
#define SYSID_TYPE "altera_avalon_sysid_qsys"


/*
 * uart1 configuration
 *
 */

#define ALT_MODULE_CLASS_uart1 altera_avalon_uart
#define UART1_BASE 0x80
#define UART1_BAUD 115200
#define UART1_DATA_BITS 8
#define UART1_FIXED_BAUD 1
#define UART1_FREQ 50000000
#define UART1_IRQ 2
#define UART1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define UART1_NAME "/dev/uart1"
#define UART1_PARITY 'N'
#define UART1_SIM_CHAR_STREAM ""
#define UART1_SIM_TRUE_BAUD 0
#define UART1_SPAN 32
#define UART1_STOP_BITS 1
#define UART1_SYNC_REG_DEPTH 2
#define UART1_TYPE "altera_avalon_uart"
#define UART1_USE_CTS_RTS 0
#define UART1_USE_EOP_REGISTER 0


/*
 * vic_0 configuration
 *
 */

#define ALT_MODULE_CLASS_vic_0 altera_vic
#define VIC_0_BASE 0x2000
#define VIC_0_DAISY_CHAIN_ENABLE 0
#define VIC_0_INTERRUPT_CONTROLLER_ID 0
#define VIC_0_IRQ -1
#define VIC_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VIC_0_NAME "/dev/vic_0"
#define VIC_0_NUMBER_OF_INT_PORTS 8
#define VIC_0_RIL_WIDTH 4
#define VIC_0_SPAN 1024
#define VIC_0_TYPE "altera_vic"

#endif /* __SYSTEM_H_ */
