#!/bin/bash

me=${0##*/}
if	[ $# -ne 1 ]
then
	echo "Usage: $me [1 "start" | 0 "stop"]" >&2
	exit 2
fi

# http://smackerelofopinion.blogspot.com/2013/05/getting-started-with-oprofile-on-ubuntu.html
# First, before running opcontrol, one may have to stop the NMI 
# watchdog to free up counter 0 using the following:
# echo "0" | sudo tee /proc/sys/kernel/watchdog

# https://www.suse.com/documentation/sles-12/singlehtml/book_sle_tuning/book_sle_tuning.html#cha.tuning.oprofile

# Kernel profiling
# http://oprofile.sourceforge.net/doc/kernel-profiling.html

# good baseline test:
#$ dd if=/dev/urandom of=/dev/null bs=4K

if [ $1 == "1" ]; then
    echo "start: $1"
    sudo opcontrol --vmlinux=/usr/lib/debug/boot/vmlinux-$(uname -r)  
    sudo opcontrol --separate=kernel  
    sudo opcontrol --init  
    sudo opcontrol --reset  
    sudo opcontrol --start  
else
    echo "stop: $1"
    sudo opcontrol --stop  
    sudo opreport image:/bin/dd -gl  
    #sudo opreport > operf.out
    sudo opcontrol --deinit  
fi

