CXX=g++
RM=rm -f
CPPFLAGS=-g -c -Wall -O0 -std=gnu++0x
LDFLAGS=-o

OBJS=vec.o vec_test.o
HEADERS=vec.h

all:	vec_test

vec_test: $(OBJS)
	$(CXX) $(LDFLAGS) $@ $+ -Wl,-Map=$@.map

%.o:%.cpp
	$(CXX) $(CPPFLAGS) $+

$(OBJS): $(HEADERS)

clean:
	$(RM) vec.o vec_test.o vec_test *.map

