#!/usr/local/bin/bash

javac FlyBehavior.java 
javac QuackBehavior.java 
javac FlyWithWings.java 
javac FlyNoWay.java 
javac FlyRocketPowered.java
javac QuackBehavior.java 
javac Quack.java 
javac Squeak.java 
javac MuteQuack.java 
javac Duck.java 
javac ModelDuck.java
javac MiniDuckSimulator.java 
java MiniDuckSimulator

